[package]
name = "hoshikasane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
ndarray = "0.15.6"
nshare = "0.9.0"
rawler = "0.6.0"