[package]
name = "hoshikasane"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
clap = { version = "4.5", features = ["derive"] }
opencv = "0.91.3"
stellacomp = { path = "stellacomp" }